[package]
name = "jch"
version = "0.1.3"
edition = "2021"
default-run = "jch"

[dependencies]
serde_json = "1.0.132"
# see also https://docs.rs/im/latest/im/
rpds = { version = "1.1", features = ["serde"] }
rmp = "0.8.14"
json-event-parser = {version = "0.2.0"}
crossbeam = "0.8"
rustc-hash = "1.1.0"
cxx = "1.0"
rtrb = "0.3"

# https://github.com/matsadler/magnus#embedding-ruby-in-rust
magnus = { version = "0.7", features = ["embed"] }
rb-sys = "0.9.102"

[build-dependencies]
cxx-build = "1.0"
